@startuml

|Zorgaanbieder|
start
:1. Lisa autoriseert MedConnect
voor endpointbeheer;

|Generieke functie Adressering|
:1a. Verifieert autorisatie;

|Dienstverlener Adressering|
:2. Jan logt in in beheeromgeving \nvan MedConnect;
:3. Jan voert endpoints in;

|Generieke functie Adressering|
:3a. Valideert endpoints en \nmaakt ze beschikbaar;

|Zorgaanbieder|
:4. Lisa logt in in beheeromgeving \nvan MedConnect;
:5. Lisa koppelt de relevante \nendpoints aan 'Medisch Centrum';

|Generieke functie Adressering|
:5a. Koppelingen tussen endpoints en \n'Medisch Centrum' zijn beschikbaar;

|Dienstverlener Adressering|
:6. Jan controleert de \nkoppelingen met de endpoints;
stop
@enduml
